@ContainerName = bccurrent
@UID = waldo
@password = 9hAmUzDbCu2Q4KRia4N8cXDYP0O09/iobggXcZWYVu4=

#@APIBaseURL = http://{{ContainerName}}:7048/BC/api/v1.0/
@APIBaseURL = http://{{ContainerName}}:7048/BC/api/waldo/alDependency/v1.0
#@APIBaseURL1 = http://{{ContainerName}}:7048/BC/api/beta

###
get {{APIBaseURL}}
Authorization: Basic {{UID}} {{password}}